opt_in_rules:
  - array_init
  - contains_over_first_not_nil
  - empty_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - sorted_first_last
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
line_length:
  - 160
  - 200
