language: generic
dist: trusty
os: linux

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

before_script:
  - swift package --version

script:
  - sh test.sh

branches:
  only:
    - master

git:
  depth: 10

sudo: false
