language: generic
dist: trusty
os: linux

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
  - sh install_swiftlint.sh ; sh lint.sh ; sh test.sh

branches:
  only:
    - master

git:
  depth: 1

sudo: false
